config/routes.rb
Rails.application.routes.draw do
  
  get 'mycal/index'
  root 'sessions#new'
  
  get 'welcome/index'
  get '/register', to: 'users#new'
  get '/about', to: 'welcome#about'
  get '/search', to: 'search#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/index_ingredient', to: 'ingredients#index'
  delete '/mycal', to: 'mycal#destroy'
  
    resources :users
    resources :ingredients
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    # has_many :mycals, dependent:   :destroy
    # has_many :users, through: :mycals
    has_many :mycals, dependent:   :destroy
    has_many :user, through: :mycals
    validates :ingredient_name, presence: true, length: { maximum: 50 }
    validates :weight, numericality: { greater_than_or_equal_to: 0 }
    validates :calorie, numericality: { greater_than_or_equal_to: 0 }
    
    def self.search(search)
        return Ingredient.where('ingredient_name LIKE ?', "%#{search}%")
    end
end

app/models/mycal.rb
class Mycal < ApplicationRecord
    # belongs_to :user
    belongs_to :ingredient
    
    validates :owner_id, presence: true
    validates :ingredient_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :mycals, dependent:   :destroy
    has_many :ingredients, through: :mycals
                                  
    before_save {self.email = email.downcase}
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:ingredient_name, :weight, :calorie)
    end
end

app/controllers/mycal_controller.rb
class MycalController < ApplicationController

  def show
  end
  
  def index
    @results = Mycal.where(owner_id: session[:user_id])
    @inge = Ingredient.all
    @total_weight = 0
    @total_calorie = 0
    @results.each do |res|
      @inge.each do |ing|
        if res.ingredient_id === ing.id
          @total_weight += ing.weight
          @total_calorie += ing.calorie
        end
      end
    end
  end
  
  def destroy
    if params[:id]
      @mycal = Mycal.find(params[:id])
      @mycal.destroy
      redirect_to mycal_index_path
    else
      @mycals = Mycal.where(owner_id: session[:user_id])
      @mycals.each do |mycalss|
        mycalss.destroy
      end
      redirect_to mycal_index_path
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def home
    if params[:search]
      @ingredients = Ingredient.all
      @isSearch = true
      @results = Ingredient.search(params[:search])
      if params[:inid] && params[:owid]
        param = {owner_id: params[:owid], ingredient_id: params[:inid]}
        @suc = Mycal.new(param)
        @suc.save
      end
    else  
      @ingredients = Ingredient.all
      @isSearch = false
    end 
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to login_path
    else
      flash.now[:danger] = 'Invalid email or password'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Register Complete!"
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                        :password_confirmation)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/mycal_helper.rb
module MycalHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end
    
    def logged_in?
        !current_user.nil?
    end
    
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
    
    # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
    
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>
      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>



  
        <div class="col-12"style="padding-left:20%;padding-right:20%; background-color:#ffffff; ">
            <br>
              <div class="field"style="padding-left:20%;padding-right:20%;">
                <%= form.label :ingredient_name %>
                <%= form.text_area :ingredient_name , :required => true %>
              </div>
               <div class="field"style="padding-left:20%;padding-right:20%;">
                <%= form.label :weight %>
                <%= form.number_field :weight , :required => true , :min => 0 %>
              </div> 
               <div class="field"style="padding-left:20%;padding-right:20%;">
                <%= form.label :calorie %>
                <%= form.number_field :calorie, :required => true, :min => 0 %>
              </div>
              <div class="actions" style="padding-left:20%;padding-right:20%;">
                <%= form.submit %>
              </div>
              <% end %>
            <br>
        </div>
    

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<div style="padding-left:1.5em;padding-right:1.5em">


<h1 class="text-center" style="font-family: 'Prompt', sans-serif;" >All Ingredients</h1>


<%= link_to '<button type="button" class="btn btn-primary btn-md align-items-right ">New Ingredient</button>'.html_safe, new_ingredient_path %>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Ingredient Name</th>
      <th scope="col">Weight(Grams)</th>
      <th scope="col">Calorie</th>
    </tr>
  </thead>
  <tbody>
    <!--<tr>-->
    <!--  <th scope="row">1</th>-->
    <!--  <td>Mark</td>-->
    <!--  <td>Otto</td>-->
    <!--  <td>@mdo</td>-->
    <!--</tr>-->
    <!--<tr>-->
    <!--  <th scope="row">2</th>-->
    <!--  <td>Jacob</td>-->
    <!--  <td>Thornton</td>-->
    <!--  <td>@fat</td>-->
    <!--</tr>-->
    <!--<tr>-->
    <!--  <th scope="row">3</th>-->
    <!--  <td>Larry</td>-->
    <!--  <td>the Bird</td>-->
    <!--  <td>@twitter</td>-->
    <!--</tr>-->
    <% @count = 0; %>
     <% @ingredients.each do |ingredient| %>
       <% @count=@count+1; %>
      <tr>
        <th scope="row"><%=@count%></th>
        <td><%= ingredient.ingredient_name %></td>
        <td><%= ingredient.weight %></td>
        <td><%= ingredient.calorie %>
        <%= link_to 'Show', ingredient %>
        <%= link_to 'Edit', edit_ingredient_path(ingredient) %>
        <%= link_to 'Delete', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<!--OLD*****************************-->

<!--END OLD **********************************-->

app/views/ingredients/new.html.erb
<h1 class="text-center" style="font-family: 'Prompt', sans-serif;">New Ingredient</h1>
<%= render 'form', ingredient: @ingredient %>

<%= link_to '<button type="button" class="btn btn-primary btn-md">Back to All Ingredient</button>'.html_safe, ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ingredient name:</strong>
  <%= @ingredient.ingredient_name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @ingredient.weight %>
</p>

<p>
  <strong>Calorie:</strong>
  <%= @ingredient.calorie %>
</p>


<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |

<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <title>Calcal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<!--link href="https://fonts.googleapis.com/css?family=Prompt" rel="stylesheet" --> 
<link href="https://fonts.googleapis.com/css?family=Comfortaa:700|Kanit|Permanent+Marker|Mali|Prompt" rel="stylesheet">
  <body>
  <style>
  .img-logo {
     width="13px"; height="7px";
    }
   .text-center .navbar{
     font-family: 'Prompt', sans-serif;
   }
  </style
  //= require_tree .
  <!--HEADER-->
    
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:#fae39c;">
  <!--<nav class="navbar navbar-expand-lg " style="background-image: url("/assets/conan.jpg");">-->
  <a class="navbar-brand"> <%= image_tag (asset_path("logo.png")),:size => "221x38"%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div  class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav pad-right" id="other">
        <div class="nav-item pad-right">
          <a class="nav-link" ><%= link_to "Home", login_path %></a>
        </div>
        <% if logged_in? %>
        <li class="nav-item pad-right">
          <a class="nav-link"><%= link_to "Search", search_path %></a>
        </li>
          <% if current_user.admin? %>
            <li class="nav-item pad-right">
              <a class="nav-link "><%= link_to 'Ingredient ( For Admin )', index_ingredient_path %></a>
            </li>
            <li class="nav-item pad-right">
              <a class="nav-link "><%= link_to 'My Cal', mycal_index_path %></a>
            </li>
          <% else %>
            <li class="nav-item pad-right">
              <a class="nav-link "><%= link_to 'My Cal', mycal_index_path %></a>
            </li>
          <% end %>
        <li class="nav-item pad-right">
          <a class="nav-link" ><%= link_to "Profile", current_user %></a>
        </li>
        <li class="nav-item pad-right">
          <a class="nav-link"><%= link_to "About", about_path %></a>
        </li>
        <li class="nav-item pad-right">
          <a class="nav-link " ><%= link_to "Log out", logout_path, method: :delete %></a>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link"><%= link_to "About", about_path %></a>
        </li>
      <% end %>
      
      <!--<li class="nav-item active">-->
      <!--  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
      <!--</li>-->
      <!--<li class="nav-item">-->
      <!--  <a class="nav-link disabled" href="#">Disabled</a>-->
      <!--</li>-->
    </ul>
  </div>
</nav>
    
    <!--END HEADER-->
    <%= yield %>
    
    <!--**********************FOOTER****************************-->
    
    <!-- <div class="containner-fluid"style="margin-top:40px;padding-top:80px; padding-bottom:80px; font-family: -->
    <!--                             'Mali', cursive; font-size: 20px;-->
    <!--                             color:#FFFFFF;-->
    <!--                             background-color: #691616; ">-->
    <!--     <div class="row"  >-->
    <!--        <div class="col-2"></div>-->
    <!--        <div class="col-8 text-center " >-->
    <!--        </div>-->


    <!--        <div class="col-2"></div>-->
    <!--    </div>-->
    <!--</div>-->
    
    
    		<footer class="footer-basic-centered">

			<p class="footer-company-motto"style="font-family: 'Prompt', sans-serif;"><i>"ความลับของการสร้างสรรค์ คือการรู้วิธีซ่อนที่มาของความคิดนั้นไว้อย่างแนบเนียน"</i></p>
        <p class="text-center footer-company-motto" style="font-family: 'Prompt', sans-serif; padding-left:25em;"><b> อัลเบิร์ต ไอน์สไตน์</b></p>
			<p class="footer-links">
				<a href="#">Home</a>
				·
				<a href="#">Blog</a>
				·
				<a href="#">Pricing</a>
				·
				<a ><%= link_to "About", about_path %></a>
				·
				<a href="#">Faq</a>
				·
				<a href="#">Contact</a>
			</p>

			<p class="footer-company-name">CalCal Limited Coporation &copy; 1997 - 2018</p>

		</footer>
    <!--***************************END FOOTER*****************************-->
  </body>
</html>

app/views/layouts/application_beforeChange.html..erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calcal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/mycal/index.html.erb
<div class="row" style="background-color:#b8e0e3;">
    <div class="col-4"></div>
    <div style="font-family: 'Mali', cursive;">
        <h1>Mycal</h1>
        <br>
        <% @results.each do |res| %>
            <% @inge.each do |ing| %>
                <% if res.ingredient_id === ing.id %>
                    <tr>
                        <td><%= ing.ingredient_name  %></td>
                        <td>น้ำหนัก <%= ing.weight %> กรัม</td>
                        <td>แคลลอรี่ <%= ing.calorie  %> แคลลอรี่<td>
                        <td><%= button_to 'Delete', mycal_path ,class: 'btn btn-outline-danger btn-sm', params: {id: res.id} , method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        <td><br></td>
                    </tr>
                <% end %>
            <% end %>
        <% end %>
        
        <% if @results.empty? %>
            <strong>Don't have any ingredient.</strong>
            <a class="nav-link"><%= link_to "Find Some!", search_path %></a>
        <% else %>
            <tr>
                <td><strong>Total Weight: <%= @total_weight %></strong></td>
                <td><strong>Total Calorie: <%= @total_calorie %></strong></td>
                <td><%= button_to 'Delete All', mycal_path, class: 'btn btn-danger btn-block' , method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
        <br>
    </div>
</div>

app/views/search/home.html.erb
<link href="https://fonts.googleapis.com/css?family=Comfortaa:700|Kanit|Permanent+Marker|Mali" rel="stylesheet">

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
 
<%= form_tag(search_path, :method => "get") do %>
    <div class="container-fluid" style="background-color:#b8e0e3;">
      <div class="row">
          <div id="demo" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ul class="carousel-indicators">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                <li data-target="#demo" data-slide-to="1"></li>
                <li data-target="#demo" data-slide-to="2"></li>
                <li data-target="#demo" data-slide-to="3"></li>
              </ul>
            
              <!-- The slideshow -->
              <div class="carousel-inner">
                <div class="carousel-item active" style="">
                  <img src="/assets/food5.png"  width=100% height=100%>
                </div>
                <div class="carousel-item">
                  <img src="/assets/food6.png"  width=100% height=100%>
                </div>
                <div class="carousel-item">
                  <img src="/assets/food7.png"  width=100% height=100%>
                </div>
                <div class="carousel-item">
                  <img src="/assets/food8.png" alt="New " width=100% height=100%>
                </div>
              </div>
            
              <!-- Left and right controls -->
              <a class="carousel-control-prev" href="#demo" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
              </a>
              <a class="carousel-control-next" href="#demo" data-slide="next">
                <span class="carousel-control-next-icon"></span>
              </a>
        
        </div>
      </div>
      <div class="row" style="padding-bottom:40px;padding-top:40px;">
        <div class="col-md-6 offset-md-3"style="padding:2rem ; ">
          <h4 class="text-center" style="color:		#8000ff;font-family: 'Prompt', sans-serif;">ทุกสิ่งที่คุณต้องการอยุ่ที่นี่แล้ว  มาเริ่มค้นหากันเลย!!</h4>
            <span><%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %></span>
            <br>
           <span ><%= submit_tag "Go", name: nil  , class: 'btn btn-primary btn-sm'%></span>
        </div>
      </div>
      <!--//RESULT SEARCH-->
    </div>
<% end %>

<script>
 $( function() {
    
    var availableTags = [
        <% @ingredients.each do |ingredient| %>
            "<%= ingredient.ingredient_name  %>",
        <% end %>
    ];
    
    $( '#search' ).autocomplete({
      source: availableTags
    });
    
 } );
</script>

<div class="container-fluid" style="background-color:#b8e0e3;">
<% if @isSearch %>
<table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Ingredient Name</th>
                  <th scope="col">Weight(Grams)</th>
                  <th scope="col">Calorie</th>
                </tr>
              </thead>
               <tbody>
              <% @count = 0; %>
    <% @results.each do |ingredient| %>
        <% @count=@count+1; %>
        <tr>
        <th scope="row"><%=@count%></th>
        <td><%= ingredient.ingredient_name  %></td>
        <td><%= ingredient.weight  %></td>
        <td><%= ingredient.calorie  %><span>
        <br><%= button_to 'Add to MyCal', search_path ,class: 'btn btn-success btn-sm', params: {search: params[:search], inid: ingredient.id, owid: session[:user_id]} , method: :get %></span></td>
        </tr>
    <% end %>
    </tbody>
</table>
<% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if@user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<!--<h1>Users#new</h1>-->
<!--<p>Find me in app/views/users/new.html.erb</p>-->
<div class="container-fluid">
    <div class="row" style=" background-color:#ccccff; ">
        <div class="col-8 offset-2" >
            <br>
            <div class="col-12" id ="h1st"><h3>Register Member</h3></div>
              <%= form_for(@user) do |f| %>
                <%= render 'shared/error_messages' %>
              
                <%=f.label :name %>
                <%=f.text_field :name, class: 'form-control' %>
                
                <%=f.label :email %>
                <%=f.email_field :email, class: 'form-control' %>
                
                <%=f.label :password %>
                <%=f.password_field :password, class: 'form-control' %>
                
                <%=f.label :password_confirmation %>
                <%=f.password_field :password_confirmation, class: 'form-control' %>
                <br>
                <%=f.submit "Submit", class: "btn btn-primary col-6 offset-3" %>
              <% end %>
            <br>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <script type="text/javascript">
function delayedRedirect(){
    window.location = "/login"
}
</script>
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <body onLoad="setTimeout('delayedRedirect()', 3000)">
    </section>
  </aside>
</div>

app/views/welcome/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Comfortaa:700|Kanit|Permanent+Marker" rel="stylesheet">
<style>
 
  #h1st{
    text-align: center ;
    font-family: 'Permanent Marker',  cursive;
    font-size: 200%;
  }
  #other{
    font-family: 'Comfortaa', cursive;
  }
</style>
<div class="container-fluid">
    <div class="row align-items-end" style="background-color:#ffccff;"> <br> </div>
    <div class="row align-items-end" style="background-color:#ffccff;">
        <div class="col-2"></div>
        <div class="col-8" id ="h1st"><h1>Welcome to CalCal</h1></div>
        <div class="col-2" id = "other"><%= link_to "Register", register_path %></div>

        <div class="col-2" id = "other"><%= link_to "About", about_path %></div>
    </div>
    <div class="row align-items-end" style="background-color:#ffccff;"> <br> </div>
    <div class="row" style=" background-color:#ccccff;">
        <div class="col-2"></div>
        <div class="col-8" style="align: center">
            <br>
            <form role="form"> 
              <div class="form-group">
                <label for="username" id = "other">Username</label>
                <input type="text" id="username" name="username" class="form-control" />
              </div>
              <div class="form-group">
                <label for="password" id = "other">Password</label>
                <input type="password" id="password" name="password" class="form-control" />
              </div>
              <input id = "other" type="submit" value="Login" />
              <input id = "other" type="button" value="Cancel" />
            </form>
            <br>
        </div>
        <div class="col-2"></div> 
    </div>
</div>